import mongoose from "mongoose";

const PROPERTY_TYPES = ["Entire Property", "Apartment/Flat", "Single Room", "Homestay"];
const AVAILABILITY_TYPES = ["For Sale", "For Rent"];

const PropertySchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, required: true },
  type: { type: String, enum: PROPERTY_TYPES, required: true },
  availability: { type: String, enum: AVAILABILITY_TYPES, required: true },
  province: { type: String, required: true },
  district: { type: String, required: true },
  municipality: { type: String, required: true },
  wardNumber: { type: String },
  streetAddress: { type: String },
  nearbyLandmark: { type: String },
  latitude: { type: Number, required: true, min: -90, max: 90 },
  longitude: { type: Number, required: true, min: -180, max: 180 },
  roadCondition: { type: String },
  roadWidth: { type: Number },
  price: { type: Number, required: true },
  securityDeposit: { type: Number },
  rentalPeriod: { type: String },
  bedrooms: { type: Number },
  bathrooms: { type: Number },
  squareFeet: { type: Number },
  builtArea: { type: Number },
  floors: { type: Number },
  yearBuilt: { type: Number },
  renovationYear: { type: Number },
  propertyFacing: { type: String },
  landOwnershipType: { type: String },
  amenities: [{ type: String }],
  electricityConnection: { type: Boolean, default: false },
  waterSupply: { type: String },
  sewageSystem: { type: String },
  gasConnection: { type: String },
  phone: { type: String, required: true },
  ownerId: { type: String, required: true },
  image: [{ type: String }],
  rating: { type: Number, default: 0 },
  createdAt: { type: Date, default: Date.now },
});

const CombinedPropertySchema = new mongoose.Schema({
  propertyId: { type: mongoose.Schema.Types.ObjectId, ref: 'Property', required: true, unique: true },
  title: { type: String, required: true },
  description: { type: String, required: true },
  type: { type: String, enum: PROPERTY_TYPES, required: true },
  availability: { type: String, enum: AVAILABILITY_TYPES, required: true },
  province: { type: String, required: true },
  district: { type: String, required: true },
  municipality: { type: String, required: true },
  wardNumber: { type: String },
  streetAddress: { type: String },
  nearbyLandmark: { type: String },
  latitude: { type: Number, required: true, min: -90, max: 90 },
  longitude: { type: Number, required: true, min: -180, max: 180 },
  roadCondition: { type: String },
  roadWidth: { type: Number },
  price: { type: Number, required: true },
  securityDeposit: { type: Number },
  rentalPeriod: { type: String },
  bedrooms: { type: Number },
  bathrooms: { type: Number },
  squareFeet: { type: Number },
  builtArea: { type: Number },
  floors: { type: Number },
  yearBuilt: { type: Number },
  renovationYear: { type: Number },
  propertyFacing: { type: String },
  landOwnershipType: { type: String },
  amenities: [{ type: String }],
  electricityConnection: { type: Boolean, default: false },
  waterSupply: { type: String },
  sewageSystem: { type: String },
  gasConnection: { type: String },
  phone: { type: String, required: true },
  ownerId: { type: String, required: true },
  image: [{ type: String }],
  rating: { type: Number, default: 0 },
  createdAt: { type: Date, default: Date.now },
});

const Property = mongoose.model("Property", PropertySchema);
const CombinedProperty = mongoose.model("CombinedProperty", CombinedPropertySchema);

export { Property, CombinedProperty };
export default { Property, CombinedProperty };